# Generated by Django 4.0.3 on 2022-05-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_employmentdetails_grade'),
        ('leave', '0003_leaveapplication_date_from_leaveapplication_date_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveduration',
            name='cadre',
        ),
        migrations.AddField(
            model_name='leaveduration',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registry.gradelevel'),
            preserve_default=False,
        ),
    ]
