# Generated by Django 4.0.3 on 2022-05-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0004_remove_leaveduration_cadre_leaveduration_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave.leaveduration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LeaveProcess',
        ),
    ]
