# Generated by Django 4.0.3 on 2022-05-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_leaveapplication_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave.leaveapplicationstatus'),
            preserve_default=False,
        ),
    ]
