# Generated by Django 4.0.3 on 2022-05-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_employmentdetails_staff_category'),
        ('leave', '0006_leaveapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveduration',
            name='grade',
        ),
        migrations.AddField(
            model_name='leaveduration',
            name='staff_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registry.staffcategory'),
            preserve_default=False,
        ),
    ]
