# Generated by Django 4.0.3 on 2022-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leaveduration_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
