# Generated by Django 4.0.3 on 2022-05-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecommendation',
            name='recommendation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.approval'),
        ),
    ]
