# Generated by Django 4.0.4 on 2022-05-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_alter_leaverecommendation_recommendation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveduration',
            name='salary_scale',
        ),
        migrations.AddField(
            model_name='leaveduration',
            name='leave_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
            preserve_default=False,
        ),
    ]
