# Generated by Django 4.0.3 on 2022-04-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_biodata_passport_alter_biodata_file_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.gender'),
        ),
    ]
