# Generated by Django 4.0.3 on 2022-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_employmentdetails_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdetails',
            name='staff_category',
            field=models.CharField(choices=[('junior', 'Junior'), ('senior', 'senior')], default='junior', max_length=15),
            preserve_default=False,
        ),
    ]
