# Generated by Django 4.0.3 on 2022-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_employmentdetails_staff_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='staff_category',
        ),
    ]
