# Generated by Django 4.0.3 on 2022-05-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_remove_leaverecommendation_comment_and_more'),
        ('registry', '0008_alter_employmentdetails_staff_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='directorate',
        ),
        migrations.RemoveField(
            model_name='directorate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Signatory',
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='directorate',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Directorate',
        ),
        migrations.DeleteModel(
            name='SubUnit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
