# Generated by Django 4.0.3 on 2022-05-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='passport'),
        ),
    ]
