# Generated by Django 4.0.3 on 2022-05-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_department_user_directorate_user_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subunit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.unit'),
        ),
    ]
